name: Python CI

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode (all | changed | path | marker)'
        required: true
        default: 'all'
      test_path:
        description: 'Path to test or test function (for mode=path)'
        required: false
      test_marker:
        description: 'Test marker (for mode=marker)'
        required: false

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libasound2t64 fonts-liberation libatk-bridge2.0-0 libatk1.0-0 libcups2 libdrm2 libxcomposite1 libxdamage1 libgbm1 libpango-1.0-0 libpangocairo-1.0-0
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run tests based on mode
      shell: bash
      run: |
        python --version
        pip --version
        python -m pytest --version

        MODE="${{ github.event.inputs.mode }}"
        PATH="${{ github.event.inputs.test_path }}"
        MARKER="${{ github.event.inputs.test_marker }}"

        echo "Mode: $MODE"
        echo "Test path: $PATH"
        echo "Marker: $MARKER"

        if [[ "$MODE" == "all" ]]; then
          python -m pytest

        elif [[ "$MODE" == "changed" ]]; then
          CHANGED_TESTS=$(git diff --name-only HEAD~1 HEAD | grep -E 'tests/.*\.py$' || true)
          echo "Changed test files: $CHANGED_TESTS"
          if [ -n "$CHANGED_TESTS" ]; then
            python -m pytest $CHANGED_TESTS
          else
            echo "No changed tests found."
          fi

        elif [[ "$MODE" == "path" ]]; then
          if [ -n "$PATH" ]; then
            python -m pytest "$PATH"
          else
            echo "Error: test_path is empty"
            exit 1
          fi

        elif [[ "$MODE" == "marker" ]]; then
          if [ -n "$MARKER" ]; then
            python -m pytest -m "$MARKER"
          else
            echo "Error: test_marker is empty"
            exit 1
          fi

        else
          echo "Invalid mode: $MODE"
          exit 1
        fi
